/* Generated By:JJTree: Do not edit this line. ASTArrayAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAccess extends SimpleNode {
  public ASTArrayAccess(int id) {
    super(id);
  }

  public ASTArrayAccess(Yal p, int id) {
    super(p, id);
  }

  public Symbol.Type getReturnType() {
    return Symbol.Type.SCALAR;
  }
  
  public boolean analyseSymbolTable() {
	  if(! verifySymbolTypes(value, true, Symbol.Type.ARRAY)) {
			System.out.println("Semantic Error: "+value +" should have been initialized to an array");
			return false;
	  }
	  else
		  return true;
  }

}
/* JavaCC - OriginalChecksum=9555d33a34fc82551229c4905477e2a1 (do not edit this line) */
