/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.io.*;

public
class ASTArgument extends SimpleNode {
  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(Yal p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
    String node = prefix + toString();

    if (this.value != null)
      node += " [" + this.value + "]";

    PrintWriter out = null;
    FileReader reader = null;
    BufferedReader br = null;

    try{
      out = new PrintWriter(new BufferedWriter(new FileWriter("output.temp")));
      reader = new FileReader("output.j");
      br = new BufferedReader(reader);
      String line;
      while ((line = br.readLine()) != null) {
        
        if (line.contains("io/print")) {
          out.println("ldc " + this.value);
          out.println("");
        }
        out.println(line);
      }

      out.close();
      reader.close();
    }catch (Exception e) {

    }


    File realName = new File("output.j");
    realName.delete();
    new File("output.temp").renameTo(realName);

    return node;
  }

}
/* JavaCC - OriginalChecksum=ca6418c9d254e6a8ef749b7e5c0a2e45 (do not edit this line) */
