/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayElement extends SimpleNode {
    public ASTArrayElement(int id) {
        super(id);
    }

    public ASTArrayElement(Yal p, int id) {
        super(p, id);
    }

    public Symbol.Type getReturnType() {
        return Symbol.Type.ARRAY;   
    }

}
/* JavaCC - OriginalChecksum=f7b64eeb7cb72cc4c48256f7dcc37f0d (do not edit this line) */
