/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
    public ASTDeclaration(int id) {
        super(id);
    }

    public ASTDeclaration(Yal p, int id) {
        super(p, id);
    }

    public boolean analyse() {
        System.out.println("Analysing " + toString(""));
        if(children == null)
            return false;

        // Declaration -> Element
        ASTElement element = (ASTElement) children[0];

        Symbol.Type type = element.getType();
        String symbolName = (String) element.jjtGetValue();

        //TODO: uncomment this when working
        //initializeSymbol((String) this.value, type, false);

        return true;
    }

}
/* JavaCC - OriginalChecksum=f0ec2df2bb99c0df69ade4aa7071b5f6 (do not edit this line) */
