/* Generated By:JJTree: Do not edit this line. ASTElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*public
class ASTElement extends SimpleNode {
  public ASTElement(int id) {
    super(id);
  }

  public ASTElement(Yal p, int id) {
    super(p, id);
  }

  public Symbol.Type getType() {
  	// Element -> ScalarElement | ArrayElement
  	Node child = children[0];

  	if(child.toString().equals("ScalarElement"))
  		return Symbol.Type.SCALAR;
  	else if(child.toString().equals("ArrayElement"))
  		return Symbol.Type.ARRAY;

  	return null;
  }

}*/
/* JavaCC - OriginalChecksum=f3539e2b8d17dcdd66d73eac4c0ec6ce (do not edit this line) */
