/* Generated By:JJTree: Do not edit this line. ASTElse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElse extends SimpleNode {
  public ASTElse(int id) {
    super(id, true, false);
  }

  public ASTElse(Yal p, int id) {
    super(p, id, true, false);
  }

}
/* JavaCC - OriginalChecksum=d1654873130fb7652e749d326e8c638f (do not edit this line) */
