/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.io.*;

public
class ASTFunction extends SimpleNode {
  public ASTFunction(int id) {
    super(id);
  }

  public ASTFunction(Yal p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
    String node = prefix + toString();

    if (this.value != null)
      node += " [" + this.value + "]";

    try(FileWriter fw = new FileWriter("output.j", true);
    BufferedWriter bw = new BufferedWriter(fw);
    PrintWriter out = new PrintWriter(bw))
    {
        out.println(".method public static " + this.value + "([Ljava/lang/String;)V");
        out.println(".limit stack 2");//need to get number
        out.println(".limit locals 2");//need to get number
        out.println("");
        out.println("return");
        out.println(".end method");
    } catch (IOException e) {
    }

    return node;
  }

}
/* JavaCC - OriginalChecksum=87cbf5972d530f3221d99b5c8270925a (do not edit this line) */
