import semantic.Symbol;

/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Yal p, int id) {
    super(p, id);
  }
  
  public Symbol.Type getReturnType() {
	  return Symbol.Type.SCALAR;
  }

}
/* JavaCC - OriginalChecksum=0d0f707e189ccad9ac7172672a0355ce (do not edit this line) */
