/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import semantic.SymbolTable;

public
class ASTIf extends SimpleNode {
	public ASTIf(int id) {
		super(id, true, false);
	}

	public ASTIf(Yal p, int id) {
		super(p, id, true, false);
	}

	public SymbolTable getAssignedSymbolTable() {
		int parentLastIndex = ((SimpleNode) parent).getLastIndex();
		return new SymbolTable(parent.getSymbolTable(), true, parentLastIndex);
	}
 
}
/* JavaCC - OriginalChecksum=8e4b5897c4afc96f6092daee5b2528aa (do not edit this line) */
