import semantic.SymbolTable;

/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
    SymbolTable functions;

    public ASTModule(int id) {
        super(id, true);
    }

    public ASTModule(Yal p, int id) {
        super(p, id, true);
    }

    public boolean analyse() {
    	 symbolTable = getAssignedSymbolTable();
    	 boolean result = true;
    	   
    	if(!analyseSymbolTable())
    			result = false;
    	
        System.out.println("Analysing " + toString(""));
        if(children == null)
            return false;

        if(!analyseFunctionHeaders()) 
            return false;

        result = true;

        for(Node child : children) {
            if(!child.analyse())
                result = false;
        }

        return result;
    }

    public boolean analyseFunctionHeaders() {
        for(Node child : children) {
            if(child.toString().equals("Function"))
                ((ASTFunction) child).analyseHeader();
        }

        return true;
    }
    
	public String generateCode() {
		String generatedCode = "";
		generatedCode += ".class public " + this.value + "\n";
		generatedCode += ".super java/lang/Object"  + "\n";
		generatedCode += "\n\n";

		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					generatedCode += n.generateCode();
				}
			}
		}
		

		return generatedCode;

	}

}
/* JavaCC - OriginalChecksum=172febbc9f462a34b5659db8744215af (do not edit this line) */
