/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
  public ASTModule(int id) {
    super(id, true);
  }

  public ASTModule(Yal p, int id) {
    super(p, id, true);
  }

}
/* JavaCC - OriginalChecksum=172febbc9f462a34b5659db8744215af (do not edit this line) */
