/* Generated By:JJTree: Do not edit this line. ASTTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTerm extends SimpleNode {
  protected String sign = null;


  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(Yal p, int id) {
    super(p, id);
  }
  
    
  public void set_sign(String sign){
  	this.sign = sign;
  }
  
  public String toString(String prefix) { 
  	String node = prefix + toString();
	

	if (this.sign != null)
		node += " [" + this.sign + this.value + "]";
	else node += " [" + this.value + "]";

    	 	
  	return node; 
  }

}
/* JavaCC - OriginalChecksum=694cdb272d61fc5ab19824a2f80bedc9 (do not edit this line) */
