import java.util.Vector;

import semantic.Symbol;
import utils.Pair;

/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(Yal p, int id) {
    super(p, id);
  }
  
  public Pair getArguments(){
	  Vector<Pair> returnVector = new Vector<Pair>();
	  Vector<Symbol.Type> returnTypes = new Vector<Symbol.Type>();
	  
	  if(children != null && children.length > 0) {
		  for(Node child : children) {
			  returnVector.add(new Pair(((SimpleNode) child).jjtGetValue(), ((SimpleNode) child).getReturnType()));
			  returnTypes.add(child.getReturnType());
		  }
	  }
	  
	  return new Pair(returnVector, returnTypes);
  }

}
/* JavaCC - OriginalChecksum=9ed7f72892898f96e09de37a40672ab4 (do not edit this line) */
