/* Generated By:JJTree: Do not edit this line. ASTArrayAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
import semantic.Symbol;
public
class ASTArrayAccess extends SimpleNode {
	public ASTArrayAccess(int id) {
		super(id);
	}

	public ASTArrayAccess(Yal p, int id) {
		super(p, id);
	}

	public Symbol.Type getReturnType() {
		return Symbol.Type.SCALAR;
	}
	
	public boolean analyseSymbolTable() {
		if(!verifySymbolTypes(getValue(), true, Symbol.Type.ARRAY)) {
			//System.out.println("Semantic Error: " + value + " should have been initialized as an array");
			printSemanticError(getValue() + " should have been initialized as an array");
			return false;
		}
		addCodeLine(this.getValue(), false);

		return true;
	}

	public String generateCode() {
		String code = "";

		// ArrayAccess -> <ID> [ Index ]

		//TODO: check if it's a static field
		// or a local variable, right now we're 
		//assuming it's always a static field

		code += "getstatic " + this.getValue();
		if(getReturnType().equals(Symbol.Type.ARRAY))
			code += " [I";
		else 
			code += " I";
		code += "\n";

		code += ((SimpleNode) getChildren()[0]).generateCode();

		code += "iaload\n";

		return code;
	}

}
/* JavaCC - OriginalChecksum=62a840c61f7e5e8fdaa8e2f68dc90bed (do not edit this line) */
