/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
import semantic.Symbol;

public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Yal p, int id) {
    super(p, id);
  }
  
  public Symbol.Type getReturnType() {
	  return Symbol.Type.SCALAR;
  }

}
/* JavaCC - OriginalChecksum=ce10658fbb3c18c01493f8bb16c7b2fe (do not edit this line) */
