/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
	  super(id, true, false, false);
  }

  public ASTWhile(Yal p, int id) {
	  super(p, id, true, false, false);
  }

}
/* JavaCC - OriginalChecksum=05929c051b300fb07e38d8870a12f1e0 (do not edit this line) */
