/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
	  super(id, true, false, false);
  }

  public ASTWhile(Yal p, int id) {
	  super(p, id, true, false, false);
  }

}
/* JavaCC - OriginalChecksum=3a70bc20f916bbbe63dce22e05aadb76 (do not edit this line) */
