/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
import semantic.Symbol;
public
class ASTArrayElement extends SimpleNode {
    public ASTArrayElement(int id) {
        super(id);
    }

    public ASTArrayElement(Yal p, int id) {
        super(p, id);
    }

    public Symbol.Type getReturnType() {
        return Symbol.Type.ARRAY;   
    }

}
/* JavaCC - OriginalChecksum=0e1d2b76b34f9185440a497dfa2969d8 (do not edit this line) */
