/* Generated By:JJTree: Do not edit this line. ASTFunctionAssign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFunctionAssign extends SimpleNode {
  public ASTFunctionAssign(int id) {
    super(id);
  }

  public ASTFunctionAssign(Yal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b8172443f5de9adf9ec7c501aa1a6e9 (do not edit this line) */
