/* Generated By:JJTree: Do not edit this line. ASTId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(Yal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c8a35ad13b0d221209b9ba46e5a3c21 (do not edit this line) */
