/* Generated By:JJTree: Do not edit this line. ASTScalarAssigned.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
import semantic.Symbol;
public
class ASTScalarAssigned extends SimpleNode {
	public ASTScalarAssigned(int id) {
		super(id);
	}

	public ASTScalarAssigned(Yal p, int id) {
		super(p, id);
	}

	public Symbol.Type getReturnType() {
		return Symbol.Type.SCALAR;
	}

}
/* JavaCC - OriginalChecksum=037e4e7ca64638c7cdb05b6eb28c263b (do not edit this line) */
