/* Generated By:JJTree: Do not edit this line. ASTScalarElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
import semantic.Symbol;
public
class ASTScalarElement extends SimpleNode {
    public ASTScalarElement(int id) {
        super(id);
    }

    public ASTScalarElement(Yal p, int id) {
        super(p, id);
    }

    public Symbol.Type getReturnType() {
        return Symbol.Type.SCALAR;
    }

}
/* JavaCC - OriginalChecksum=7cacf00a7d2f33ffcfd7ff0ba70ab2bc (do not edit this line) */
