/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;
import java.util.Vector;
import semantic.Symbol;
import utils.Pair;
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(Yal p, int id) {
    super(p, id);
  }
  
  public Pair getArguments(){
	  Vector<Pair> returnVector = new Vector<Pair>();
	  Vector<Symbol.Type> returnTypes = new Vector<Symbol.Type>();
	  
	  if(getChildren() != null && getChildren().length > 0) {
		  for(Node child : getChildren()) {
			  returnVector.add(new Pair(((SimpleNode) child).jjtGetValue(), ((SimpleNode) child).getReturnType()));
			  returnTypes.add(((SimpleNode) child).getReturnType());
		  }
	  }
	  
	  return new Pair(returnVector, returnTypes);
  }

}
/* JavaCC - OriginalChecksum=ffa231bc6ab0e00a1fcc01b86f709f89 (do not edit this line) */
