/* Generated By:JJTree: Do not edit this line. ASTFunctionAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionAssign extends SimpleNode {
  public ASTFunctionAssign(int id) {
    super(id);
  }

  public ASTFunctionAssign(Yal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=136ecee0911ef6f0db4a8efeae00e005 (do not edit this line) */
