/* Generated By:JJTree: Do not edit this line. ASTId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(Yal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa1cb54a7e76fd468c07275c07ab446a (do not edit this line) */
