/* Generated By:JavaCC: Do not edit this line. YalTreeConstants.java Version 6.0_1 */
public interface YalTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMODULE = 1;
  public int JJTDECLARATION = 2;
  public int JJTARRAYASSIGNED = 3;
  public int JJTSCALARASSIGNED = 4;
  public int JJTFUNCTION = 5;
  public int JJTFUNCTIONASSIGN = 6;
  public int JJTVARLIST = 7;
  public int JJTVOID = 8;
  public int JJTARRAYELEMENT = 9;
  public int JJTSCALARELEMENT = 10;
  public int JJTASSIGN = 11;
  public int JJTRHS = 12;
  public int JJTARRAYSIZE = 13;
  public int JJTTERM = 14;
  public int JJTINTEGER = 15;
  public int JJTEXPRTEST = 16;
  public int JJTWHILE = 17;
  public int JJTIFSTATEMENT = 18;
  public int JJTIF = 19;
  public int JJTELSE = 20;
  public int JJTCALL = 21;
  public int JJTARGUMENT = 22;
  public int JJTID = 23;
  public int JJTSTRING = 24;
  public int JJTARRAYACCESS = 25;
  public int JJTSCALARACCESS = 26;
  public int JJTINDEX = 27;


  public String[] jjtNodeName = {
    "Program",
    "Module",
    "Declaration",
    "ArrayAssigned",
    "ScalarAssigned",
    "Function",
    "FunctionAssign",
    "Varlist",
    "void",
    "ArrayElement",
    "ScalarElement",
    "Assign",
    "Rhs",
    "ArraySize",
    "Term",
    "Integer",
    "Exprtest",
    "While",
    "IfStatement",
    "If",
    "Else",
    "Call",
    "Argument",
    "Id",
    "String",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=d925d715359e5fd72b11f8b784c79c21 (do not edit this line) */
